version: '2'

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: mariadb:latest
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
        
  php:
    container_name: ${PROJECT_NAME}
    build: ./docker/php
    links:
      - db
    volumes:
      - ./www/:/var/www

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build: ./docker/nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php

  phpmyadmin:
    container_name: ${PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    links:
      - db
    ports:
      - '8080:80'
